"""
Launch Readiness PDF Service
Generates a professional PDF report for go-live certification
"""
import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


def build_launch_readiness_pdf(report: dict):
    """Build a professional launch readiness PDF report"""
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Colors
    navy = colors.HexColor("#20364D")
    gold = colors.HexColor("#D4A843")
    text = colors.HexColor("#0F172A")
    muted = colors.HexColor("#64748B")
    soft = colors.HexColor("#F8FAFC")
    green = colors.HexColor("#22C55E")
    red = colors.HexColor("#EF4444")

    # Header
    c.setFillColor(navy)
    c.rect(0, height - 40 * mm, width, 40 * mm, stroke=0, fill=1)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(18 * mm, height - 20 * mm, "KONEKT LAUNCH READINESS REPORT")
    
    c.setFont("Helvetica", 10)
    c.drawString(18 * mm, height - 28 * mm, f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    c.drawRightString(width - 18 * mm, height - 28 * mm, "System Version: v1.0")

    # Overall Status Section
    c.setFillColor(text)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(18 * mm, height - 55 * mm, "Overall Status")

    # Status card
    c.setFillColor(soft)
    c.roundRect(18 * mm, height - 80 * mm, width - 36 * mm, 20 * mm, 3 * mm, stroke=0, fill=1)

    c.setFillColor(text)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(26 * mm, height - 68 * mm, f"Readiness Score: {report.get('ready_score', 0)}/{report.get('max_score', 0)}")
    
    status = report.get("status", "needs_attention")
    c.setFillColor(green if status == "ready" else gold)
    c.setFont("Helvetica-Bold", 14)
    c.drawRightString(width - 26 * mm, height - 68 * mm, status.upper().replace("_", " "))

    # Checks Section
    y = height - 95 * mm
    c.setFillColor(text)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(18 * mm, y, "Configuration Checks")
    y -= 10 * mm

    c.setFont("Helvetica", 10)
    for key, value in report.get("checks", {}).items():
        # Draw checkbox
        c.setFillColor(soft)
        c.roundRect(24 * mm, y - 1 * mm, 5 * mm, 5 * mm, 1 * mm, stroke=0, fill=1)
        
        if value:
            c.setFillColor(green)
            c.setFont("Helvetica-Bold", 10)
            c.drawString(25 * mm, y, "✓")
        
        c.setFillColor(text)
        c.setFont("Helvetica", 10)
        c.drawString(32 * mm, y, key.replace("_", " ").title())
        
        c.setFillColor(green if value else red)
        c.setFont("Helvetica-Bold", 10)
        c.drawRightString(width - 24 * mm, y, "OK" if value else "MISSING")
        
        y -= 8 * mm

    # Data Counts Section
    y -= 8 * mm
    c.setFillColor(text)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(18 * mm, y, "Data Counts")
    y -= 10 * mm

    c.setFont("Helvetica", 10)
    counts = report.get("counts", {})
    
    # Two columns for counts
    count_items = list(counts.items())
    mid = len(count_items) // 2 + len(count_items) % 2
    
    for i, (key, value) in enumerate(count_items[:mid]):
        c.setFillColor(text)
        c.drawString(24 * mm, y, key.replace("_", " ").title())
        c.setFillColor(navy)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(80 * mm, y, str(value))
        c.setFont("Helvetica", 10)
        
        if i < len(count_items) - mid:
            key2, value2 = count_items[mid + i]
            c.setFillColor(text)
            c.drawString(110 * mm, y, key2.replace("_", " ").title())
            c.setFillColor(navy)
            c.setFont("Helvetica-Bold", 10)
            c.drawString(165 * mm, y, str(value2))
            c.setFont("Helvetica", 10)
        
        y -= 7 * mm

    # Manual Checklist Section
    y -= 10 * mm
    c.setFillColor(text)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(18 * mm, y, "Manual Final Checklist")
    y -= 10 * mm

    checklist = report.get("manual_checklist", [])
    c.setFont("Helvetica", 9)
    c.setFillColor(muted)
    
    for item in checklist:
        if y < 25 * mm:
            c.showPage()
            y = height - 25 * mm
            c.setFillColor(muted)
            c.setFont("Helvetica", 9)
        
        c.drawString(24 * mm, y, "□")
        c.drawString(32 * mm, y, item)
        y -= 7 * mm

    # Footer
    c.setStrokeColor(colors.HexColor("#E2E8F0"))
    c.line(18 * mm, 18 * mm, width - 18 * mm, 18 * mm)
    
    c.setFillColor(muted)
    c.setFont("Helvetica", 8)
    c.drawString(18 * mm, 12 * mm, "This report was automatically generated by Konekt Business OS")
    c.drawRightString(width - 18 * mm, 12 * mm, "Confidential - Internal Use Only")

    c.save()
    buffer.seek(0)
    return buffer
