import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { Receipt, Eye, AlertCircle } from "lucide-react";
import PageHeader from "../../components/ui/PageHeader";
import SurfaceCard from "../../components/ui/SurfaceCard";
import FilterBar from "../../components/ui/FilterBar";
import BrandButton from "../../components/ui/BrandButton";
import axios from "axios";
const API_URL = process.env.REACT_APP_BACKEND_URL || "";
const STATUS_LABELS = { pending_payment: 'Awaiting Payment', pending: 'Awaiting Payment', awaiting_payment_proof: 'Awaiting Payment', payment_under_review: 'Under Review', payment_proof_uploaded: 'Under Review', proof_uploaded: 'Under Review', payment_rejected: 'Rejected', proof_rejected: 'Rejected', paid: 'Paid', partially_paid: 'Partially Paid' };
const STATUS_COLORS = { pending_payment: 'bg-amber-100 text-amber-800', pending: 'bg-amber-100 text-amber-800', awaiting_payment_proof: 'bg-amber-100 text-amber-800', payment_under_review: 'bg-blue-100 text-blue-800', payment_proof_uploaded: 'bg-blue-100 text-blue-800', proof_uploaded: 'bg-blue-100 text-blue-800', payment_rejected: 'bg-red-100 text-red-700', proof_rejected: 'bg-red-100 text-red-700', paid: 'bg-green-100 text-green-800', partially_paid: 'bg-orange-100 text-orange-800' };
function money(v){ return `TZS ${Number(v||0).toLocaleString()}`; }
function fmtDate(v){ try { return new Date(v).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});} catch { return '-'; } }
export default function InvoicesPageV2(){
 const [invoices,setInvoices]=useState([]); const [loading,setLoading]=useState(true); const [searchValue,setSearchValue]=useState(''); const [statusFilter,setStatusFilter]=useState('');
 useEffect(()=>{ const token=localStorage.getItem('token'); if(!token) return; axios.get(`${API_URL}/api/customer/invoices`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>setInvoices(r.data||[])).catch(e=>console.error(e)).finally(()=>setLoading(false)); },[]);
 const filtered = invoices.filter(invoice=>{ const ref=`${invoice.invoice_number||''} ${invoice.id||''}`.toLowerCase(); return (!searchValue || ref.includes(searchValue.toLowerCase())) && (!statusFilter || (invoice.payment_status||invoice.status)===statusFilter); });
 const unpaidTotal = invoices.filter(i=>i.status!=='paid').reduce((s,i)=>s+Number(i.total||i.total_amount||0),0);
 return <div className="space-y-6" data-testid="invoices-page"><PageHeader title="Invoices" subtitle="Track payments, review finance feedback, and open invoice details." />
 {unpaidTotal>0 && <SurfaceCard className="bg-amber-50 border-amber-200"><div className="flex items-center gap-3"><AlertCircle className="w-5 h-5 text-amber-600"/><span className="font-medium text-amber-800">You have {money(unpaidTotal)} awaiting payment or review.</span></div></SurfaceCard>}
 <FilterBar searchValue={searchValue} onSearchChange={setSearchValue} searchPlaceholder="Search by invoice number..." filters={[{name:'status',value:statusFilter,onChange:setStatusFilter,placeholder:'All Statuses',options:[{value:'pending_payment',label:'Awaiting Payment'},{value:'payment_under_review',label:'Under Review'},{value:'payment_rejected',label:'Rejected'},{value:'paid',label:'Paid'}]}]} />
 <SurfaceCard className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-4 py-3 text-left font-semibold">Date</th><th className="px-4 py-3 text-left font-semibold">Invoice</th><th className="px-4 py-3 text-left font-semibold">Type</th><th className="px-4 py-3 text-left font-semibold">Amount</th><th className="px-4 py-3 text-left font-semibold">Payment Status</th><th className="px-4 py-3 text-left font-semibold">Notes</th><th className="px-4 py-3 text-right font-semibold">Actions</th></tr></thead><tbody>
 {loading ? <tr><td colSpan="7" className="px-4 py-10 text-center text-slate-500">Loading invoices...</td></tr> : filtered.length ? filtered.map(invoice=>{ const state=invoice.payment_status||invoice.status||'pending_payment'; return <tr key={invoice.id||invoice._id} className="border-t hover:bg-slate-50/60"><td className="px-4 py-4 whitespace-nowrap text-slate-600">{fmtDate(invoice.created_at)}</td><td className="px-4 py-4"><div className="font-semibold text-[#20364D]">{invoice.invoice_number||invoice.id?.slice(-8)}</div><div className="text-xs text-slate-500">{invoice.source_type||invoice.type||'invoice'}</div></td><td className="px-4 py-4 text-slate-600">{(invoice.type||invoice.source_type||'general').replace(/_/g,' ')}</td><td className="px-4 py-4 font-semibold text-[#20364D]">{money(invoice.total||invoice.total_amount)}</td><td className="px-4 py-4"><span className={`px-3 py-1 rounded-full text-xs font-semibold ${STATUS_COLORS[state]||'bg-slate-100 text-slate-700'}`}>{STATUS_LABELS[state]||state}</span></td><td className="px-4 py-4 text-xs text-slate-600 max-w-[220px]">{invoice.rejection_reason||'-'}</td><td className="px-4 py-4"><div className="flex justify-end gap-2">{state!=='paid' && <BrandButton href={`/dashboard/invoices/${invoice.id||invoice._id}/pay`} variant="gold" className="text-xs py-2">{state==='payment_rejected'?'Resubmit Proof':'Pay Invoice'}</BrandButton>}<Link to={`/dashboard/invoices/${invoice.id||invoice._id}`} className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 hover:bg-slate-50"><Eye className="w-4 h-4"/><span>View</span></Link></div></td></tr>; }) : <tr><td colSpan="7" className="px-4 py-12 text-center text-slate-500"><Receipt className="w-12 h-12 mx-auto mb-3 text-slate-300"/><div className="font-semibold text-[#20364D] mb-1">No invoices yet</div><div>Invoices from product orders and approved service or promo quotes will appear here.</div></td></tr>}
 </tbody></table></div></SurfaceCard></div>; }
