"""
Session 6 regression tests — pre-deployment backlog sweep.
Covers:
  • GET /api/admin/reports/country-breakdown/pdf  → valid PDF
  • POST /api/admin/vendor-agreements/nudge-unsigned → runs (may warn on sandbox domain)
  • QR attachment in quote/invoice PDFs (generated bytes non-empty, contains %PDF header)
  • Weekly digest deliver_digest email path is safe to call when Resend unset
"""
import os
import pytest
import httpx
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient

API_URL = os.environ.get("REACT_APP_BACKEND_URL") or "http://localhost:8001"
ADMIN_EMAIL = "admin@konekt.co.tz"
ADMIN_PW = "KnktcKk_L-hw1wSyquvd!"

_cached_token = None
def admin_token():
    global _cached_token
    if _cached_token:
        return _cached_token
    r = httpx.post(f"{API_URL}/api/auth/login", json={"email": ADMIN_EMAIL, "password": ADMIN_PW}, timeout=20)
    assert r.status_code == 200
    d = r.json()
    _cached_token = d.get("token") or d.get("access_token")
    return _cached_token


def test_country_breakdown_pdf():
    r = httpx.get(f"{API_URL}/api/admin/reports/country-breakdown/pdf?period=month", timeout=30)
    assert r.status_code == 200
    assert r.headers["content-type"] == "application/pdf"
    assert r.content[:4] == b"%PDF"
    assert len(r.content) > 500


def test_country_breakdown_pdf_various_periods():
    for period in ["week", "month", "quarter", "year"]:
        r = httpx.get(f"{API_URL}/api/admin/reports/country-breakdown/pdf?period={period}", timeout=30)
        assert r.status_code == 200
        assert r.content[:4] == b"%PDF"


def test_nudge_unsigned_endpoint_reachable():
    tok = admin_token()
    r = httpx.post(f"{API_URL}/api/admin/vendor-agreements/nudge-unsigned",
                   headers={"Authorization": f"Bearer {tok}"}, timeout=60)
    # Either all signed (0 sent) OR we get counts
    assert r.status_code == 200
    j = r.json()
    assert "unsigned_count" in j and "sent" in j


def test_commercial_pdf_with_qr_includes_image():
    """Run generate_commercial_document_pdf directly and ensure QR attach doesn't break render."""
    import sys
    sys.path.insert(0, "/app/backend")
    from pdf_commercial_documents import generate_commercial_document_pdf
    doc = {
        "id": "test-doc-1",
        "invoice_number": "INV-TEST-001",
        "client_name": "Test Client",
        "items": [{"name": "Widget", "quantity": 2, "unit_price": 1000, "total": 2000}],
        "subtotal": 2000,
        "total": 2000,
    }
    settings = {"company_name": "Konekt", "default_payment_terms": "Net 30"}
    buf = generate_commercial_document_pdf(doc, settings, document_type="invoice")
    data = buf.getvalue()
    assert data[:4] == b"%PDF"
    assert len(data) > 2000
    # The QR file should have been created on disk under /app/static/qr/invoices
    from pathlib import Path
    qr_file = Path("/app/static/qr/invoices/test-doc-1.png")
    assert qr_file.exists()
    assert qr_file.stat().st_size > 100


@pytest.mark.asyncio
async def test_weekly_digest_deliver_no_resend_safe():
    """deliver_digest must be safe even when RESEND_API_KEY is unset (degrades to in-app only)."""
    import sys
    sys.path.insert(0, "/app/backend")
    from services.weekly_digest import deliver_digest
    cli = AsyncIOMotorClient(os.environ["MONGO_URL"])
    db = cli[os.environ["DB_NAME"]]
    # Deliver with a minimal digest — should not raise
    before = os.environ.get("RESEND_API_KEY")
    os.environ.pop("RESEND_API_KEY", None)
    try:
        await deliver_digest(db, {
            "period": "test-week",
            "task_pipeline": "x",
            "partner_performance": "y",
            "revenue_flow": "z",
            "alerts": "a",
        })
    finally:
        if before:
            os.environ["RESEND_API_KEY"] = before
