export const adminNavigation = [
  {
    key: "ecosystem",
    label: "Ecosystem Control",
    moduleKey: "dashboard",
    children: [
      { label: "Ecosystem Dashboard", href: "/admin/ecosystem-dashboard", moduleKey: "dashboard" },
      { label: "Group Markups", href: "/admin/group-markups", moduleKey: "settings" },
      { label: "Partner Settlements", href: "/admin/partner-settlements", moduleKey: "finance" },
      { label: "Payment Proofs", href: "/admin/payment-proofs", moduleKey: "finance" },
    ],
  },
  {
    key: "overview",
    label: "Overview",
    moduleKey: "dashboard",
    children: [
      { label: "Dashboard", href: "/admin", moduleKey: "dashboard" },
      { label: "Launch Readiness", href: "/admin/launch-readiness", moduleKey: "settings" },
      { label: "CRM Intelligence", href: "/admin/crm-intelligence", moduleKey: "crm" },
    ],
  },
  {
    key: "sales",
    label: "Sales",
    moduleKey: "crm",
    children: [
      { label: "CRM", href: "/admin/crm", moduleKey: "crm" },
      { label: "Quotes", href: "/admin/quotes", moduleKey: "quotes" },
      { label: "Customers", href: "/admin/customers", moduleKey: "customers" },
      { label: "Customer Accounts", href: "/admin/customer-accounts", moduleKey: "customers" },
      { label: "Contract Clients", href: "/admin/contract-clients", moduleKey: "customers" },
    ],
  },
  {
    key: "operations",
    label: "Operations",
    moduleKey: "orders",
    children: [
      { label: "Orders", href: "/admin/orders", moduleKey: "orders" },
      { label: "Order Operations", href: "/admin/orders-ops", moduleKey: "orders" },
      { label: "Service Requests", href: "/admin/service-requests", moduleKey: "orders" },
      { label: "Production", href: "/admin/production", moduleKey: "production" },
      { label: "Tasks", href: "/admin/tasks", moduleKey: "tasks" },
    ],
  },
  {
    key: "inventory",
    label: "Inventory",
    moduleKey: "inventory",
    children: [
      { label: "Products", href: "/admin/products", moduleKey: "inventory" },
      { label: "Inventory & Variants", href: "/admin/inventory", moduleKey: "inventory" },
      { label: "Stock Movements", href: "/admin/inventory/movements", moduleKey: "inventory" },
      { label: "Transfers", href: "/admin/inventory/transfers", moduleKey: "inventory" },
      { label: "Warehouses", href: "/admin/warehouses", moduleKey: "inventory" },
      { label: "Raw Materials", href: "/admin/raw-materials", moduleKey: "inventory" },
    ],
  },
  {
    key: "finance",
    label: "Finance",
    moduleKey: "finance",
    children: [
      { label: "Invoices", href: "/admin/invoices", moduleKey: "finance" },
      { label: "Central Payments", href: "/admin/central-payments", moduleKey: "finance" },
      { label: "Record Payment", href: "/admin/payments/record", moduleKey: "finance" },
      { label: "Statements", href: "/admin/statements", moduleKey: "finance" },
      { label: "Document Flow", href: "/admin/workflow", moduleKey: "finance" },
      { label: "Negotiated Pricing", href: "/admin/negotiated-pricing", moduleKey: "finance" },
      { label: "Contract SLAs", href: "/admin/contract-slas", moduleKey: "finance" },
      { label: "Recurring Invoices", href: "/admin/recurring-invoice-plans", moduleKey: "finance" },
    ],
  },
  {
    key: "marketing",
    label: "Marketing",
    moduleKey: "marketing",
    children: [
      { label: "Hero Banners", href: "/admin/hero-banners", moduleKey: "marketing" },
      { label: "Creative Services", href: "/admin/creative-services", moduleKey: "marketing" },
      { label: "Referral Settings", href: "/admin/referral-settings", moduleKey: "marketing" },
      { label: "Affiliates", href: "/admin/affiliates", moduleKey: "marketing" },
      { label: "Affiliate Applications", href: "/admin/affiliate-applications", moduleKey: "marketing" },
    ],
  },
  {
    key: "service_orchestration",
    label: "Service Orchestration",
    moduleKey: "services",
    children: [
      { label: "Service Catalog", href: "/admin/service-catalog", moduleKey: "services" },
      { label: "Blank Products", href: "/admin/blank-products", moduleKey: "services" },
    ],
  },
  {
    key: "performance_insights",
    label: "Performance & Insights",
    moduleKey: "reports",
    children: [
      { label: "Partner Performance", href: "/admin/partner-performance", moduleKey: "reports" },
      { label: "Product Insights", href: "/admin/product-insights", moduleKey: "reports" },
      { label: "Service Insights", href: "/admin/service-insights", moduleKey: "reports" },
      { label: "Staff Performance", href: "/admin/staff-performance", moduleKey: "reports" },
    ],
  },
  {
    key: "sla_quality",
    label: "SLA & Quality",
    moduleKey: "reports",
    children: [
      { label: "SLA Alerts", href: "/admin/sla-alerts", moduleKey: "reports" },
    ],
  },
  {
    key: "settings",
    label: "Settings",
    moduleKey: "settings",
    children: [
      { label: "Business Settings", href: "/admin/business-settings", moduleKey: "settings" },
      { label: "CRM Settings", href: "/admin/crm-settings", moduleKey: "crm" },
      { label: "Company Settings", href: "/admin/settings/company", moduleKey: "settings" },
      { label: "Setup", href: "/admin/setup", moduleKey: "settings" },
      { label: "Users", href: "/admin/users", moduleKey: "settings" },
      { label: "Audit Log", href: "/admin/audit", moduleKey: "audit" },
    ],
  },
];
